#define CODE_BUILD_TIME_YEAR 20
#define CODE_BUILD_TIME_MONTH 12
#define CODE_BUILD_TIME_DATE 25
#define CODE_BUILD_TIME_HOUR 9
#define CODE_BUILD_TIME_MINUTE 24
#define CODE_BUILD_TIME_SECOND 2
